image: quay.io/sheogorath/build-ah-engine

variables: 
  LANG: C.UTF-8

before_script:
  - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - analyse
  - build
  - test
  - tag
  - deploy

build:
  stage: build
  script:
    - podman build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - podman push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

tagging-master:
  stage: tag
  script:
    - podman pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - si-tagging -l "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE" "$(grep -e 'FROM docker.io/gitlab/gitlab-runner:v' Dockerfile | sed -e 's/.*:v//')"
    - podman images --format "{{.Repository}}:{{.Tag}}" "$CI_REGISTRY_IMAGE" | grep "$CI_REGISTRY_IMAGE" | xargs -L 1 podman push
  only:
    - master

